elk:
        restart: always
        image: reg.qiniu.com/pub/elk:6
        ports:
                - "11118:22"
                - "11140:9200"
        volumes:
                - /app:/app
        container_name: elk
        hostname: elk
        command:
                - /bin/bash
                - -c
                - |
                        cron
                        /usr/sbin/sshd -D
                        #external_links:
                        #- base
        privileged: true
